### ISSUE TITLE
Add environment configuration option to set terminal background color

### ISSUE THREAD

**Issue by igorshubovych** [jingweno/ccat#4]
I use dark terminal. It is a pain to write every time ```--bg "dark"```.
It should be simple to read some environment variable (or any other type of global configuration file, e.g. ~/.ccat file) and define it globally. Then command line argument can just overwrite the global configuration, if present.

P.S. I want to add that light scheme looks ok on dark terminal, but i use dark terminal with transparency and only then it is unreadable. As it is unreadable for small portion of users, i do not think it is critical.

**Comment by jingweno** [comment]
:+1: I plan to support this!

**Comment by jingweno** [comment]
@igorshubovych The [color scheme](https://github.com/jingweno/ccat/blob/master/printer.go#L12-L40) is not optimized. Feel free to help improve this. I also plan to make the color scheme customizable so that you could define yours. I pre-populate a bunch of color codes [here](https://github.com/jingweno/ccat/blob/master/colorize.go#L11).

**Comment by jingweno** [comment]
Actually just another thought. How about `alias ccat="ccat --bg=dark"`?

**Comment by igorshubovych** [comment]
Good idea

**Comment by jingweno** [comment]
@igorshubovych I made a PR to provide options to set color values: https://github.com/jingweno/ccat/pull/27
